### ISSUE TITLE
training take long time

### ISSUE THREAD

**Issue by essamgoda** [dashayushman/deep-trans#6]
i have Nvidia 940mx 4gb when I run training on my own data (different languages)

if i use 

`--size=1024 --num_layers=5 --steps_per_checkpoint=1000`

it stop in this line for more 15 minutes 

`I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 2059 to `  

when i use smaller size and less layers 
`--size=512 --num_layers=2 --steps_per_checkpoint=1000`

the result is

```
global step 1000 learning rate 0.0010 step-time 0.19 perplexity 1861.61
  eval: empty bucket 0
  eval: bucket 1 perplexity 6.93
  eval: bucket 2 perplexity 6.45
  eval: empty bucket 3
  eval: empty bucket 4
  eval: empty bucket 5
global step 2000 learning rate 0.0010 step-time 0.20 perplexity 4.04
  eval: empty bucket 0
  eval: bucket 1 perplexity 2.84
  eval: bucket 2 perplexity 3.03
  eval: empty bucket 3
  eval: empty bucket 4
  eval: empty bucket 5
global step 3000 learning rate 0.0010 step-time 0.20 perplexity 2.27
  eval: empty bucket 0
  eval: bucket 1 perplexity 2.12
  eval: bucket 2 perplexity 2.09
  eval: empty bucket 3
  eval: empty bucket 4
  eval: empty bucket 5
```

and continue to more and more step take more than 2 hours and not finish 

how ever it small data just few words.

**Comment by dashayushman** [comment]
@essamgoda : This model will take time because of the number of parameters. I usually train the models for days.
